BASE_YAML: "COCO-Detection/faster_rcnn_R_101_C4_3x.yaml"
DATASETS:
        TRAIN: ("daytime_clear_train",)
        TEST: ('daytime_clear_test',)
DATALOADER:
        NUM_WORKERS: 16
        ASPECT_RATIO_GROUPING: True
INPUT:
        MIN_SIZE_TRAIN: (600,)
        MIN_SIZE_TEST: 600
        CLIP_RANDOM_CROPS: True
        RANDOM_CROP_SIZE: 400

SOLVER:
        BASE_LR: 0.001
        MAX_ITER: 100000
        STEPS: [40000,]       
        WARMUP_ITERS: 0
        IMS_PER_BATCH: 4
        CHECKPOINT_PERIOD: 1000000
MODEL:
        BACKBONE:
                NAME: ClipRN101
                FREEZE_AT: 2
                UNFREEZE:
                - layer3
                - layer4
                - attnpool
        WEIGHTS: ""
        CLIP_IMAGE_ENCODER_NAME: 'RN101'
        META_ARCHITECTURE: 'ClipRCNNWithClipBackboneTrainable'

        PROPOSAL_GENERATOR:
                NAME: 'SBRPN'
        ROI_HEADS:
                NAME: 'ClipRes5ROIHeadsAttn'        
                NUM_CLASSES: 7
TEST:
        EVAL_SAVE_PERIOD: 5000

OUTPUT_DIR: "all_outs/diverse_weather"
VIS_PERIOD: 5000

